# Generated by Django 5.1.4 on 2024-12-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Главное', 'verbose_name_plural': 'Главное'},
        ),
        migrations.RemoveField(
            model_name='main',
            name='Image',
        ),
        migrations.AddField(
            model_name='main',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='image/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
